INSERT INTO RESULT(id, name) VALUES (1, 'PLAYER_WIN');
INSERT INTO RESULT(id, name) VALUES (2, 'COMPUTER_WIN');
INSERT INTO RESULT(id, name) VALUES (3, 'DRAW');

INSERT INTO player VALUES ('ab18c338-b95e-4a2a-aa04-2e950d9fa909')